In [111]:
import pickle
import pandas as pd

# Specify the path to the pickle file
train_pickle_file_path = 'airflow_files_train_preprocessed_ddfaf_csv_new.pickle'
val_pickle_file_path = 'airflow_files_inference_preprocessed_ddfaf_csv.pickle'

# Load the pickled data from the file into a DataFrame
with open(train_pickle_file_path, 'rb') as f:
    preprocessed_train_df = pickle.load(f).reset_index()
    
with open(val_pickle_file_path, 'rb') as f:
    preprocessed_val_df = pickle.load(f).reset_index()

In [115]:
preprocessed_train_df

,index,Index,From_ID,To_ID,Timestamp,Amount_Paid,Payment_Currency,Amount_Received,Receiving_Currency,Payment_Format,...,from_degree,from_in_degree,from_out_degree,from_clustering_coeff,from_degree_centrality,to_degree,to_in_degree,to_out_degree,to_clustering_coeff,to_degree_centrality
0,0,0,0,1,550.0,859.84,0,859.84,0,0,...,2,1,1,0.0,0.000029,1,1,0,0.0,0.000014
1,1,1,2,3,1450.0,48.78,0,48.78,0,1,...,1,0,1,0.0,0.000014,1,1,0,0.0,0.000014
2,2,2,4,5,730.0,315.86,0,315.86,0,1,...,1,0,1,0.0,0.000014,1,1,0,0.0,0.000014
3,3,3,6,7,1090.0,20.76,0,20.76,0,1,...,2,1,1,0.0,0.000029,2,2,0,0.0,0.000029
4,4,4,8,9,1690.0,1917.90,0,1917.90,0,2,...,1,0,1,0.0,0.000014,1,1,0,0.0,0.000014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,79995,79995,40,21256,1030.0,27354.43,0,27354.43,0,4,...,836,1,835,0.0,0.012073,4,2,2,0.0,0.000058
79996,79996,79996,21502,21503,1690.0,2159.72,0,2159.72,0,1,...,2,0,2,0.0,0.000029,1,1,0,0.0,0.000014
79997,79997,79997,69243,69243,70.0,163.61,0,163.61,0,3,...,2,1,1,0.0,0.000029,2,1,1,0.0,0.000029
79998,79998,79998,69244,69244,730.0,10.28,0,10.28,0,3,...,2,1,1,0.0,0.000029,2,1,1,0.0,0.000029
79999,79999,79999,22221,22221,490.0,23.90,0,23.90,0,3,...,3,2,1,0.0,0.000043,3,2,1,0.0,0.000043

In [116]:
preprocessed_train_df.columns

Index(['index', 'Index', 'From_ID', 'To_ID', 'Timestamp', 'Amount_Paid',
       'Payment_Currency', 'Amount_Received', 'Receiving_Currency',
       'Payment_Format', 'Is_Laundering', 'from_degree', 'from_in_degree',
       'from_out_degree', 'from_clustering_coeff', 'from_degree_centrality',
       'to_degree', 'to_in_degree', 'to_out_degree', 'to_clustering_coeff',
       'to_degree_centrality'],
      dtype='object')

In [145]:
preprocessed_train_df[:40000][preprocessed_train_df['Is_Laundering'] == 1]

<ipython-input-145-04f8da867f09>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  preprocessed_train_df[:40000][preprocessed_train_df['Is_Laundering'] == 1]

,index,Index,From_ID,To_ID,Timestamp,Amount_Paid,Payment_Currency,Amount_Received,Receiving_Currency,Payment_Format,...,from_degree,from_in_degree,from_out_degree,from_clustering_coeff,from_degree_centrality,to_degree,to_in_degree,to_out_degree,to_clustering_coeff,to_degree_centrality
16752,16752,16752,40,18936,1270.0,389769.39,0,389769.39,0,4,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043
27967,27967,27967,40,2767,190.0,29024.33,0,29024.33,0,1,...,836,1,835,0.0,0.012073,1,1,0,0.0,0.000014
30149,30149,30149,40,23667,190.0,13171425.53,0,13171425.53,0,4,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043
33871,33871,33871,40,629,1390.0,14288.83,0,14288.83,0,0,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043

In [118]:
train_X = preprocessed_train_df.drop(columns=['Is_Laundering', 'Index', 'index'])
train_y = preprocessed_train_df['Is_Laundering']
val_X = preprocessed_val_df.drop(columns=['Is_Laundering', 'Index', 'index'])
val_y = preprocessed_val_df['Is_Laundering']

In [119]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler to your data and transform it
normalized_data = scaler.fit_transform(train_X)
# Convert the normalized data back to a DataFrame
train_X = pd.DataFrame(normalized_data, columns=train_X.columns)

# Fit the scaler to your data and transform it
normalized_data = scaler.fit_transform(val_X)
# Convert the normalized data back to a DataFrame
val_X = pd.DataFrame(normalized_data, columns=val_X.columns)

In [120]:
train_X

,From_ID,To_ID,Timestamp,Amount_Paid,Payment_Currency,Amount_Received,Receiving_Currency,Payment_Format,from_degree,from_in_degree,from_out_degree,from_clustering_coeff,from_degree_centrality,to_degree,to_in_degree,to_out_degree,to_clustering_coeff,to_degree_centrality
0,0.000000,0.000014,0.310345,1.606814e-07,0.0,1.606814e-07,0.0,0.000000,0.001198,0.111111,0.000000,0.0,0.001198,0.000000,0.000,0.000000,0.0,0.000000
1,0.000029,0.000043,0.827586,9.115109e-09,0.0,9.115109e-09,0.0,0.166667,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000,0.000000,0.0,0.000000
2,0.000058,0.000072,0.413793,5.902551e-08,0.0,5.902551e-08,0.0,0.166667,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000,0.000000,0.0,0.000000
3,0.000087,0.000101,0.620690,3.878890e-09,0.0,3.878890e-09,0.0,0.166667,0.001198,0.111111,0.000000,0.0,0.001198,0.001198,0.125,0.000000,0.0,0.001198
4,0.000116,0.000130,0.965517,3.584057e-07,0.0,3.584057e-07,0.0,0.333333,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,0.000578,0.306972,0.586207,5.111841e-06,0.0,5.111841e-06,0.0,0.666667,1.000000,0.111111,1.000000,0.0,1.000000,0.003593,0.125,0.002395,0.0,0.003593
79996,0.310525,0.310540,0.965517,4.035957e-07,0.0,4.035957e-07,0.0,0.166667,0.001198,0.000000,0.001199,0.0,0.001198,0.000000,0.000,0.000000,0.0,0.000000
79997,0.999986,0.999986,0.034483,3.057389e-08,0.0,3.057389e-08,0.0,0.500000,0.001198,0.111111,0.000000,0.0,0.001198,0.001198,0.000,0.001198,0.0,0.001198
79998,1.000000,1.000000,0.413793,1.920447e-09,0.0,1.920447e-09,0.0,0.500000,0.001198,0.111111,0.000000,0.0,0.001198,0.001198,0.000,0.001198,0.0,0.001198
79999,0.320909,0.320909,0.275862,4.465675e-09,0.0,4.465675e-09,0.0,0.500000,0.002395,0.222222,0.000000,0.0,0.002395,0.002395,0.125,0.001198,0.0,0.002395

In [121]:
preprocessed_train_df[preprocessed_train_df['Is_Laundering'] == 1]

,index,Index,From_ID,To_ID,Timestamp,Amount_Paid,Payment_Currency,Amount_Received,Receiving_Currency,Payment_Format,...,from_degree,from_in_degree,from_out_degree,from_clustering_coeff,from_degree_centrality,to_degree,to_in_degree,to_out_degree,to_clustering_coeff,to_degree_centrality
16752,16752,16752,40,18936,1270.0,389769.39,0,389769.39,0,4,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043
27967,27967,27967,40,2767,190.0,29024.33,0,29024.33,0,1,...,836,1,835,0.0,0.012073,1,1,0,0.0,0.000014
30149,30149,30149,40,23667,190.0,13171425.53,0,13171425.53,0,4,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043
33871,33871,33871,40,629,1390.0,14288.83,0,14288.83,0,0,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043
56689,56689,56689,40,43817,70.0,792.92,0,792.92,0,1,...,836,1,835,0.0,0.012073,3,2,1,0.0,0.000043

In [123]:
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Lambda
from tensorflow.keras.losses import MeanSquaredError, KLDivergence
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

# Assuming train_X, train_y, val_X, val_y are already defined

# Define and train a Variational Autoencoder
input_dim = train_X.shape[1]
latent_dim = 10  # Choose an appropriate latent dimension

# Define the encoder
encoder_inputs = Input(shape=(input_dim,))
encoded = Dense(128, activation='relu')(encoder_inputs)
z_mean = Dense(latent_dim)(encoded)
z_log_var = Dense(latent_dim)(encoded)

# Define the sampling layer
def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(shape=(K.shape(z_mean)[0], latent_dim),
                              mean=0., stddev=1.)
    return z_mean + K.exp(0.5 * z_log_var) * epsilon

z = Lambda(sampling)([z_mean, z_log_var])

# Define the decoder
decoder_inputs = Input(shape=(latent_dim,))
decoded = Dense(128, activation='relu')(decoder_inputs)
decoded_outputs = Dense(input_dim, activation='sigmoid')(decoded)

# Define the models
encoder = Model(encoder_inputs, z_mean)
decoder = Model(decoder_inputs, decoded_outputs)
decoder_outputs = decoder(z)
vae = Model(encoder_inputs, decoder_outputs)

# Define the VAE loss
reconstruction_loss = MeanSquaredError()(encoder_inputs, decoder_outputs)
kl_loss = KLDivergence()(z_mean, z_log_var)
vae_loss = reconstruction_loss + kl_loss
vae.add_loss(vae_loss)
vae.compile(optimizer=Adam())

# Train the VAE
vae.fit(train_X, epochs=10, batch_size=32, validation_data=(val_X, None))

# Generate synthetic samples for minority class
minority_class_indices = np.where(train_y == 1)[0]
minority_class_samples = train_X.iloc[minority_class_indices]
synthetic_samples = vae.predict(minority_class_samples)

# Combine original and synthetic samples
X_train_balanced = np.concatenate([train_X, synthetic_samples], axis=0)
y_train_balanced = np.concatenate([train_y, np.ones(len(synthetic_samples))], axis=0)

# Optionally, you can further balance the dataset using SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_balanced, y_train_balanced)

# Now, you can train your classifier using X_train_resampled and y_train_resampled

Epoch 1/10
2500/2500 [==============================] - 14s 5ms/step - loss: -2.8801 - val_loss: -2.7282
Epoch 2/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9381 - val_loss: -2.7237
Epoch 3/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9405 - val_loss: -2.7693
Epoch 4/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9409 - val_loss: -2.7468
Epoch 5/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9413 - val_loss: -2.8040
Epoch 6/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9415 - val_loss: -2.7463
Epoch 7/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9415 - val_loss: -2.8273
Epoch 8/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9415 - val_loss: -2.7649
Epoch 9/10
2500/2500 [==============================] - 13s 5ms/step - loss: -2.9416 - val_loss: -2.8184
Epoch 10/10
2500/2500 [==============================] - 14s 5ms/step - loss: -2.9415 - val_loss: -2.7311
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x2cf7a1310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/1 [==============================] - 0s 73ms/step

In [124]:
len(y_train_resampled)

159990

In [140]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Create and fit the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the validation set
y_pred = rf_classifier.predict(train_X.head(40000))

# Evaluate the classifier
print("Accuracy: ", accuracy_score(train_y[:40000], y_pred))

# Evaluate the classifier
print(classification_report(train_y[:40000], y_pred))

Accuracy:  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     39996
           1       1.00      1.00      1.00         4

    accuracy                           1.00     40000
   macro avg       1.00      1.00      1.00     40000
weighted avg       1.00      1.00      1.00     40000

/Users/vishalbns/miniforge3/envs/mldl/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [141]:
len(y_pred[y_pred == 1])

4

In [142]:
len(y_pred)

40000

In [143]:
# Records that have been marked by model to be fraudulent and have to reviewed by human
train_X.head(40000)[y_pred==1]

,From_ID,To_ID,Timestamp,Amount_Paid,Payment_Currency,Amount_Received,Receiving_Currency,Payment_Format,from_degree,from_in_degree,from_out_degree,from_clustering_coeff,from_degree_centrality,to_degree,to_in_degree,to_out_degree,to_clustering_coeff,to_degree_centrality
16752,0.000578,0.273468,0.724138,0.000073,0.0,0.000073,0.0,0.666667,1.0,0.111111,1.0,0.0,1.0,0.002395,0.125,0.001198,0.0,0.002395
27967,0.000578,0.039960,0.103448,0.000005,0.0,0.000005,0.0,0.166667,1.0,0.111111,1.0,0.0,1.0,0.000000,0.000,0.000000,0.0,0.000000
30149,0.000578,0.341791,0.103448,0.002461,0.0,0.002461,0.0,0.666667,1.0,0.111111,1.0,0.0,1.0,0.002395,0.125,0.001198,0.0,0.002395
33871,0.000578,0.009084,0.793103,0.000003,0.0,0.000003,0.0,0.000000,1.0,0.111111,1.0,0.0,1.0,0.002395,0.125,0.001198,0.0,0.002395

In [99]:
import pickle
with open('hi_medium_df.pickle', 'wb') as f:
    pickle.dump(hi_medium, f)

In [108]:
hi_small_trans = pd.read_csv('HI_Small_Trans.csv')
hi_small_trans = hi_small_trans.head(20000)
import pickle
with open('HI_Small_Trans.pickle', 'wb') as f:
    pickle.dump(hi_small_trans, f)

In [110]:
hi_small_trans = pd.read_csv('HI_Small_Trans.csv')
hi_small_trans = hi_small_trans.head(500)

# Save DataFrame to CSV
hi_small_trans.to_csv('HI_Small_Trans_500.csv', index=False)